# image property will be set during release
image:
  repository: ~
  tag: ~

# hostname that is resolvable via DNS
# will also be used as the ingress host if ingress is enabled
# e.g. s.ingress.<shootname>.<project>.shoot.<landscape>.k8s-hana.ondemand.com
host: "localhost"

port: 8080

log:
  # enable/disable dev logging
  dev: false

replicaCount: 1

# name of a image pull secret for pulling the image (optional)
imagePullSecretName: ""

# name of a secret that contains the private key for signing in PEM format
privateKeySecretName: ""

# name of a configmap that contains the server certificate in PEM format
certificateConfigMapName: ""

# name of a configmap that contains the concatenation of any intermediate and ca certificate in PEM format (optional)
caCertificatesConfigMapName: ""

# max body size in bytes
maxBodySize: 2048

# disable authentication. should only be used for development
disableAuth: false

ingress:
  # if disabled, the server is only exposed cluster internally via ClusterIP service
  enabled: false
  auth:
    username: ""
    password: ""
