{{- if .Values.ingress.enabled }}
apiVersion: v1
data:
  auth: {{ htpasswd .Values.ingress.auth.username .Values.ingress.auth.password | b64enc }}
kind: Secret
metadata:
  name: {{ template "signing-server.fullname" . }}-auth
  labels:
    app: {{ template "signing-server.fullname" . }}
type: Opaque
{{- end }}