apiVersion: v1
kind: Service
metadata:
  name: {{ template "signing-server.fullname" . }}
  labels:
    app: {{ template "signing-server.fullname" . }}
spec:
  selector:
    app: {{ template "signing-server.fullname" . }}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: {{ .Values.port }}