name: Build

on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the mode to use. either `snapshot` or `release`. Will affect effective version, as well
          as target-oci-registry.

jobs:
  prepare:
    uses: gardener/cc-utils/.github/workflows/prepare.yaml@master
    permissions:
      contents: read
    with:
      mode: ${{ inputs.mode }}

  oci-images:
    name: Build OCI-Images
    uses: gardener/cc-utils/.github/workflows/oci-ocm.yaml@master
    needs:
      - prepare
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      name: signing-server
      version: ${{ needs.prepare.outputs.version }}
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: cicd/signing-server
      oci-platforms: linux/amd64
      ctx: oci-images

  helmcharts:
    name: Build Helmcharts
    uses: gardener/cc-utils/.github/workflows/helmchart-ocm.yaml@master
    needs:
      - prepare
      - oci-images
    permissions:
      contents: read
      packages: write
      id-token: write
    with:
      name: signing-server
      dir: chart
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: cicd/charts
      ocm-mappings: |
        - ref: ocm-resource:signing-server.repository
          attribute: image.repository
        - ref: ocm-resource:signing-server.tag
          attribute: image.tag
